

CREATE DATABASE IF NOT EXISTS clinica2;

USE clinica2;

CREATE TABLE MEDICO(
NUMEROCRM BIGINT NOT NULL,
ESTADOCRM CHAR(2) NOT NULL,
NOMEMED VARCHAR (100) NOT NULL, 
 
CONSTRAINT MEDICO_PK PRIMARY KEY (NUMEROCRM,ESTADOCRM)
) ENGINE = INNODB;

CREATE TABLE PACIENTE (
ID INT NOT NULL AUTO_INCREMENT,
SEXO ENUM ( "F", "M") NOT NULL,
CIDADE VARCHAR (30) NOT NULL,
ESTADO CHAR (2) NOT NULL,
COMPLEMENTO VARCHAR (100),
CEP BIGINT NOT NULL,
DATANASCIMENTO DATE NOT NULL,
NOMEPAC VARCHAR (100) NOT NULL,

CONSTRAINT PACIENTE_PK PRIMARY KEY (ID) 

) ENGINE = INNODB;

CREATE TABLE ESPECIALIDADE (
IDESPEC INT NOT NULL AUTO_INCREMENT,
NOMEESPEC VARCHAR (30) NOT NULL,
CONSTRAINT ESPECIALIDADE_PK PRIMARY KEY (IDESPEC)
)ENGINE  = INNODB;

CREATE TABLE POSSUIESPECIALDADE (
IDESPEC INT  NOT NULL,
NUMEROCRM BIGINT NOT NULL,
ESTADOCRM CHAR (2) NOT NULL,
 CONSTRAINT POSSUI_ESPECIALIDADE_UK UNIQUE (IDESPEC, NUMEROCRM, ESTADOCRM),
 CONSTRAINT POSSUI_MEDICO_FK FOREIGN KEY (NUMEROCRM,ESTADOCRM)
 REFERENCES MEDICO(NUMEROCRM, ESTADOCRM)
 ON DELETE CASCADE,
 CONSTRAINT POSSUI_ESPECIALIDADE_FK FOREIGN KEY (IDESPEC)
 REFERENCES ESPECIALIDADE (IDESPEC)
ON DELETE CASCADE 
)ENGINE = INNODB;


CREATE TABLE CONSULTA (
IDCONS INT NOT NULL AUTO_INCREMENT,
DATAHORA TIMESTAMP NOT NULL,
NUMEROCRM BIGINT NOT NULL,
ESTADOCRM CHAR (2) NOT NULL,
IDPACIENTE INT NOT NULL,

CONSTRAINT CONSULTA_PK PRIMARY KEY (IDCONS),
CONSTRAINT CONSULTA_MEDICO_FK FOREIGN KEY (NUMEROCRM,ESTADOCRM)
REFERENCES MEDICO(NUMEROCRM, ESTADOCRM)
ON DELETE CASCADE,
CONSTRAINT CONSULTA_PACIENTE_FK FOREIGN KEY (IDPACIENTE)
REFERENCES PACIENTE (ID)
ON DELETE CASCADE
)ENGINE = INNODB;

CREATE TABLE TELEFONE (
TELEFONE DECIMAL (11) NOT NULL,
IDPACIENTE INT NOT NULL,

CONSTRAINT TELEFONE_UK UNIQUE (TELEFONE, IDPACIENTE),
CONSTRAINT TELEFONE_CONSULTA_PACIENTE_FK FOREIGN KEY (IDPACIENTE)
REFERENCES PACIENTE (ID)
ON DELETE CASCADE
 
)ENGINE = INNODB;

CREATE TABLE RECEITA (
IDRECEITA INT NOT NULL AUTO_INCREMENT ,
IDCONS INT NOT NULL,
DESCRICAO VARCHAR (100),

CONSTRAINT IDRECEITA_PK PRIMARY KEY (IDRECEITA),
CONSTRAINT IDCONS_FK FOREIGN KEY (IDCONS) 
         REFERENCES CONSULTA (IDCONS)
         ON DELETE CASCADE 
)ENGINE = INNODB;

CREATE TABLE MEDICAMENTOPRES (
MEDICAMENTO VARCHAR (100) NOT NULL, 
IDRECEITA INT  NOT NULL,

  CONSTRAINT IDRECEITA_FK FOREIGN KEY (IDRECEITA)
   REFERENCES RECEITA (IDRECEITA)
   ON DELETE CASCADE 
   
) ENGINE = INNODB;

