USE CLINICA2;
CREATE VIEW MEDICO_ESPECIALIDADE_GINECOLOGIA (NOMEMED, NUMEROCRM,ESTADOCRM )
AS SELECT M.NOMEMED, M.NUMEROCRM, M.ESTADOCRM FROM MEDICO M, POSSUIESPECIALIDADE PE 
WHERE M.NUMEROCRM = PE.NUMEROCRM  AND PE.IDESPEC = 1;

SELECT *FROM PACIENTE WHERE NOMEPAC LIKE '%FERNANDES%';
