

CREATE DATABASE IF NOT EXISTS clinica2;

USE clinica2;

CREATE TABLE MEDICO(
NUMEROCRM BIGINT NOT NULL,
ESTADOCRM CHAR(2) NOT NULL,
NOMEMED VARCHAR (100) NOT NULL, 
 
CONSTRAINT MEDICO_PK PRIMARY KEY (NUMEROCRM,ESTADOCRM)
 
) ENGINE = INNODB;

CREATE TABLE PACIENTE (
ID INT NOT NULL AUTO_INCREMENT,
SEXO ENUM ( "F", "M") NOT NULL,
CIDADE VARCHAR (30) NOT NULL,
ESTADO CHAR (2) NOT NULL,
COMPLEMENTO VARCHAR (100),
CEP BIGINT NOT NULL,
DATANASCIMENTO DATE NOT NULL,
NOMEPAC VARCHAR (100) NOT NULL,

CONSTRAINT PACIENTE_PK PRIMARY KEY (ID) 

) ENGINE = INNODB;

