USE papelaria;
CREATE VIEW BUCARFUNCIONARIO AS
SELECT NOMEFUNCIONARIO,IDMATRICULA 
	FROM FUNCIONARIO 
		WHERE FUNCAO = 'Vendedor';
        
select f.IDMATRICULA, F.NOMEFUNCIONARIO, F. FUNCAO
	FROM FUNCIONARIO F LEFT JOIN VENDAS V
        ON F.IDMATRICULA = v.IDMATRICULA
        WHERE V.IDMATRICULA IS NULL;
        
        -- Quero descobrir, qual o fornecedor teve mais produtos vendidos?
        
        SELECT P.NOMEPRODUTO AS 'NOME DO PRODUTO', SUM(P.PRECO*LP.QNTVENDIDO) AS 'TOTAL',
        SUM(LP.QNTVENDIDO) AS 'QUANTIDADE'
        FROM PRODUTO P
         INNER JOIN LISTAPRODUTOS LP 
          ON P.IDPRODUTO = LP.IDPRODUTO
             GROUP BY P.NOMEPRODUTO;
             
        
        