SELECT NOMEFUNCIONARIO,IDMATRICULA 
	FROM FUNCIONARIO 
		WHERE FUNCAO = 'Vendedor';
        
select f.IDMATRICULA, F.NOMEFUNCIONARIO, F. FUNCAO
	FROM FUNCIONARIO F LEFT JOIN VENDAS V
        ON F.IDMATRICULA = v.IDMATRICULA
        WHERE V.IDMATRICULA IS NULL;