CREATE DATABASE IF NOT EXISTS PAPELARIA;
USE PAPELARIA;

CREATE TABLE FUNCIONARIO (
IDMATRICULA INT NOT NULL AUTO_INCREMENT,
NOMEFUNCIONARIO VARCHAR (100) NOT NULL,
FUNCAO VARCHAR (50) NOT NULL,
EMAIL VARCHAR (50),

CONSTRAINT FUNCIONARIO_PK PRIMARY KEY ( IDMATRICULA ) 
 
)ENGINE=INNODB;

CREATE TABLE CLIENTE (
NOMECLIENTE VARCHAR (50),
CPF BIGINT NOT NULL,
EMAIL VARCHAR (50) NOT NULL,
ENDERECO VARCHAR  (100),

CONSTRAINT CLIENTE_PK PRIMARY KEY (CPF)

)ENGINE= INNODB ;

CREATE TABLE FORNECEDOR (
CNPJ INT NOT NULL,
NOMEFORNECEDOR VARCHAR ( 50 ) NOT NULL,
TELEFOFORNECEDOR BIGINT NOT NULL,
EMAILFORNECEDOR  VARCHAR (50) NOT NULL, 
ENDERECOFORNECEDOR VARCHAR (100 ) NOT NULL,

CONSTRAINT FORNECEDOR_PK PRIMARY KEY (CNPJ) 
) ENGINE = INNODB;

CREATE TABLE PRODUTO ( 
IDPRODUTO INT NOT NULL AUTO_INCREMENT,
PRECO INT NOT NULL,
VALIDADE DATE,
NOMEPRODUTO VARCHAR (50) NOT NULL,
DESCRICAO VARCHAR (50) NOT NULL,
QUANTIDADE INT NOT NULL,
CNPJ INT NOT NULL,

CONSTRAINT PRODUTO_PK PRIMARY KEY  (IDPRODUTO),
CONSTRAINT PRODUTO_FORNECEDOR_FK FOREIGN KEY  (CNPJ)
REFERENCES FORNECEDOR (CNPJ)
ON DELETE CASCADE 

) ENGINE = INNODB;

CREATE TABLE VENDA (
IDMATRICULA INT NOT NULL,
CPF BIGINT NOT NULL,
IDVENDA INT NOT NULL AUTO_INCREMENT,
)


