-- LIVIA DE JESUS GOMES CURADO 
-- RA: 72301395


CREATE DATABASE IF NOT EXISTS CEUBINHO;
USE CEUBINHO;

CREATE TABLE ESTUDANTE
(
ID_MATRICULA INT NOT NULL AUTO_INCREMENT,
NOME_ALUNO VARCHAR (100)NOT NULL,
EMAIL VARCHAR (100) NOT NULL,
ENDERECO VARCHAR (200) NOT NULL,
TELEFONE BIGINT (11) NOT NULL,

CONSTRAINT ESTUDANTE_PK PRIMARY KEY (ID_MATRICULA)

)ENGINE = INNODB;

CREATE TABLE PROFESSOR
(
ID_PROF INT NOT NULL AUTO_INCREMENT,
NOME_PROF VARCHAR (100) NOT NULL,
EMAIL VARCHAR (100) NOT NULL, 
TELEFONE BIGINT (11) NOT NULL,

CONSTRAINT PROFESSOR_PK PRIMARY KEY(ID_PROF)

) ENGINE = INNODB;

CREATE TABLE DISCIPLINA
(
ID_DISCI INT NOT NULL AUTO_INCREMENT,
NOME_DISCI VARCHAR (100) NOT NULL,
CREDITOS INT NOT NULL,
ID_PROF INT,

CONSTRAINT DISCIPLINA_PK PRIMARY KEY (ID_DISCI),

CONSTRAINT DISCIPLINA_PROFESSOR_FK FOREIGN KEY (ID_PROF)
REFERENCES PROFESSOR (ID_PROF)
ON DELETE CASCADE 
)ENGINE = INNODB,AUTO_INCREMENT = 100;

CREATE TABLE DEPARTAMENTO 
(
ID_PROF INT NOT NULL,
NOME_DEPARTAMENTO VARCHAR (100),

CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY (NOME_DEPARTAMENTO),
CONSTRAINT DEPARTAMENTO_PROFESSOR_FK foreign key (ID_PROF)
REFERENCES PROFESSOR (ID_PROF)
ON DELETE CASCADE 
)ENGINE = INNODB;

CREATE TABLE CURSO 
(
CODIGO_CURSO INT NOT NULL AUTO_INCREMENT,
NOME_CURSO VARCHAR (50),
NOME_DEPARTAMENTO VARCHAR (100),

CONSTRAINT CURSO_PK PRIMARY KEY (CODIGO_CURSO),
CONSTRAINT CURSO_DEPARTAMENTO_FK FOREIGN KEY (NOME_DEPARTAMENTO)
REFERENCES DEPARTAMENTO (NOME_DEPARTAMENTO)
ON DELETE CASCADE 

)ENGINE = INNODB;

CREATE TABLE MATRICULA_DISCIPLINA
(
ID_DISCI INT NOT NULL,
ID_MATRICULA INT NOT NULL,
SEMESTRE INT NOT NULL,
SALA INT,
TURNO VARCHAR (50),

CONSTRAINT MATRICULA_DISCIPLINA_ESTUDANTE_FK FOREIGN KEY (ID_MATRICULA)
REFERENCES ESTUDANTE (ID_MATRICULA)
ON DELETE CASCADE,

CONSTRAINT MATRICULA_DISCIPLINA_DISCIPLINA_FK FOREIGN KEY (ID_DISCI)
REFERENCES DISCIPLINA (ID_DISCI)
ON DELETE CASCADE 
)ENGINE = INNODB;
